<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BGLPF2ANKWJ" failures="2" tests="4" name="Test1" time="16.439" errors="0" timestamp="2022-09-04T00:57:36 IST">
  <testcase classname="pkg1.Assertions" name="Verify1" time="0.049">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at pkg1.Assertions.Verify1(Assertions.java:26)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Verify1 -->
  <testcase classname="pkg1.Assertions" name="Verify2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [Saikiaa] but found [Saikia]">
      <![CDATA[java.lang.AssertionError: expected [Saikiaa] but found [Saikia]
at pkg1.Assertions.Verify2(Assertions.java:31)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Verify2 -->
  <testcase classname="pkg1.Assertions" name="VerifyWebTitle" time="0.024"/>
  <testcase classname="pkg1.Samplehello1" name="Hellosample1" time="0.02"/>
</testsuite> <!-- Test1 -->
